services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: ypm-user
      POSTGRES_PASSWORD: ypm-password
      POSTGRES_DB: ypm-db
    ports:
      - '5432:5432'
    volumes:
      - ypm-data:/var/lib/postgresql

  db-test:
    image: postgres:18
    environment:
      POSTGRES_USER: ypm-user
      POSTGRES_PASSWORD: ypm-password
      POSTGRES_DB: ypm-test
    ports:
      - '5433:5432'
    tmpfs:
      - /var/lib/postgresql

volumes:
  ypm-data:
